### ISSUE TITLE
[Bug] After installing error output 500" 

### ISSUE THREAD

**Issue by hedho** [FOSSBilling/FOSSBilling#1986]
### Describe the bug

[17-Dec-2023 15:33:32 UTC] SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;4solution_fozzbilliz.extension&#039; doesn&#039;t exist
[17-Dec-2023 15:34:03 UTC] Unknown &quot;DebugBar_renderHead&quot; function.
[17-Dec-2023 15:34:44 UTC] Page /grand-laboratoire-jaune-m-2n805Vug not found
[17-Dec-2023 15:34:44 UTC] Unknown &quot;DebugBar_renderHead&quot; function.
[17-Dec-2023 15:35:46 UTC] Page /hoodie-mhysa-noir-the-north-face-l-exception-mm-0pBWGfq not found
[17-Dec-2023 15:35:46 UTC] Unknown &quot;DebugBar_renderHead&quot; function.
[17-Dec-2023 15:35:47 UTC] Page /veste-lee-91b-sherpa-mm-2ebAMtg not found
[17-Dec-2023 15:35:47 UTC] Unknown &quot;DebugBar_renderHead&quot; function.
[17-Dec-2023 15:36:05 UTC] Page /abris-de-bûcher-mm-5AAbMgFa not found
[17-Dec-2023 15:36:05 UTC] Unknown &quot;DebugBar_renderHead&quot; function.
[17-Dec-2023 15:37:48 UTC] Unknown &quot;DebugBar_renderHead&quot; function.

### How to reproduce

Simply download official latest stable .. and try ot install !

Erorr logs:

```
[17-Dec-2023 15:33:57 UTC] PHP Warning:  Undefined array key "error_reporting" in /home/uzik/web/gind.uzik.no/public_html/install/install.php on line 114
[17-Dec-2023 15:33:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method FOSSBilling\Version::isPreviewVersion() in /home/uzik/web/gind.uzik.no/public_html/install/install.php:403
Stack trace:
#0 /home/uzik/web/gind.uzik.no/public_html/install/install.php(387): FOSSBilling_Installer->getConfigOutput()
#1 /home/uzik/web/gind.uzik.no/public_html/install/install.php(136): FOSSBilling_Installer->install()
#2 /home/uzik/web/gind.uzik.no/public_html/install/install.php(75): FOSSBilling_Installer->run()
#3 {main}
  thrown in /home/uzik/web/gind.uzik.no/public_html/install/install.php on line 403
```

### Expected behavior

After installing !

### FOSSBilling version

0.6.3

### Device

Desktop

**Comment by BelleNottelling** [comment]
Please try performing a clean install after re-downloading the release.

**Comment by hedho** [comment]
This is output out of a "clean install" !

**Comment by epichosts** [comment]
What are the PHP and MySQL/MariaDB server versions you are using?

**Comment by hedho** [comment]
> What are the PHP and MySQL/MariaDB server versions you are using?

Php version: 8.2 
Mysql version: 8.1.26

All running stable version !

**Comment by hedho** [comment]
Now it's installing but the issue is this:

```
An error has occurred.

Instance ID: 7cf84423-d197-4dbf-8a3d-72f313f0c1ae Error Code: #0 Component: Generic
You've received a generic error message: . An exception has been thrown during the rendering of a template ("Could not find the entry "fossbilling" in "/home/4solution/web/gind/public_html/themes/huraga/build/entrypoints.json". Found: huraga, markdown."). .
```

**Comment by evrifaessa** [comment]
@hedho - Hey, does this issue still persist? Can you try again with another clean install? Thanks.
